### ISSUE TITLE
The design of the website is totally broken on Firefox

### ISSUE THREAD

**Issue by stof** [cathydutton/cathydutton.co.uk#7]
Here is a screenshot in Chromium: 
![image](https://user-images.githubusercontent.com/439401/96019685-29b60f00-0e4d-11eb-88ce-e0906d1437b8.png)

And here is the same screenshot in Firefox: 
![image](https://user-images.githubusercontent.com/439401/96019759-45211a00-0e4d-11eb-818f-9537fb64bc69.png)

I'm quite sure that the Chromium screenshot corresponds better to the intended behavior.

Looking at the console, there is also a JS error in Firefox:

```
Uncaught TypeError: r is null
```

The location of the error corresponds to this code:

```js
r = document.getElementById('theme-contrast') // variable r is defined here
// ...

r.addEventListener('click', function (e) { // error happens here
    t.className = 'theme-contrast',
    localStorage.setItem('currentTheme', 'theme-contrast')
  }),
```

**Comment by stof** [comment]
Forcing a reload (with `Ctrl+F5`) fixed it, so it might have been an issue related to a stale cache in service worker, or something like that

**Comment by cathydutton** [comment]
Thanks, I haven't been able to replicate this. But have updated the version in my ServiceWorker file. Maybe that will fix it.

**Comment by stof** [comment]
I cannot replicate it anymore, as I did a force refresh and so I don't have the old cache anymore.
